name: jm_dict
description: Implementation of the Open Source JMdict Japanese Dictionary
  Project as a Flutter plugin.
version: 0.2.0
repository: https://github.com/nsNeruno/jm_dict

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  archive: ^3.3.1
  flutter:
    sdk: flutter
  kana_kit: ^2.0.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  path_provider: ^2.0.11
  platform: ^3.1.0
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  objectbox_generator: ^4.0.2

objectbox:
  output_dir: src/objectbox
